server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: admin
    url: jdbc:mysql://localhost:3306/algero
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql

v1Api : api/v1